(function(){
var qs=new URLSearchParams(location.search),daily=qs.get('mode')!=='practice',round=0,score=0,results=[],locked=false,timer=null,current=null,KEY='oneoff-v1',started=Date.now();
var seed=daily?hash(new Date().toLocaleDateString('en-CA')):(Date.now()>>>0);
function hash(s){var h=2166136261,i;for(i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rnd(){seed|=0;seed=(seed+0x6D2B79F5)|0;var t=seed;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}
function ri(a,b){return Math.floor(rnd()*(b-a+1))+a}
var modes=['pick','type','slider','flash','pick'];
function make(){return{mode:modes[round],target:ri(12,88)}}
function el(id){return document.getElementById(id)}
function render(){clearInterval(timer);locked=false;current=make();el('roundText').textContent='ROUND '+(round+1)+'/5';el('target').textContent=current.target;el('feedback').textContent='';el('feedback').className='feedback';el('nextBtn').classList.add('hidden');el('dots').innerHTML='';for(var d=0;d<5;d++){var x=document.createElement('i');x.className='dot '+(d<results.length?(results[d]?'good':'bad'):'');el('dots').appendChild(x)}el('arena').innerHTML='';var m=current.mode,t=current.target;el('modeLabel').textContent={pick:'PICK ONE',type:'TYPE IT',slider:'SLIDE IT',flash:'QUICK TAP'}[m];
if(m==='pick'){el('instruction').textContent=round===4?'Final round. One perfect miss.':'Choose exactly ONE away.';var sign=rnd()>.5?1:-1,win=t+sign,vals=[win,t,t+(sign*2),t+(sign*3)];shuffle(vals);var box=document.createElement('div');box.className='choice-grid';vals.forEach(function(v){var b=document.createElement('button');b.className='choice';b.textContent=v;b.onclick=function(){answer(v)};box.appendChild(b)});el('arena').appendChild(box)}
if(m==='type'){el('instruction').textContent='No choices. Type a number exactly ONE away.';el('arena').innerHTML='<input class="number-input" id="num" inputmode="numeric" placeholder="?"><button class="primary submit" id="submit">LOCK IT</button>';el('submit').onclick=function(){var n=el('num');if(n.value!=='')answer(Number(n.value))}}
if(m==='slider'){el('instruction').textContent='Slide fast. Stop exactly ONE away.';el('arena').innerHTML='<div class="slider-wrap"><div class="slider-label" id="sv">50</div><input id="range" class="slider" type="range" min="1" max="100" value="50"><div class="range-ends"><span>1</span><span>100</span></div></div><button class="primary" id="lock">LOCK IT</button>';var r=el('range');r.oninput=function(){el('sv').textContent=r.value};el('lock').onclick=function(){answer(Number(r.value))}}
if(m==='flash'){el('instruction').textContent='Numbers move fast. Tap the big number when it is exactly ONE away.';var sign=rnd()>.5?1:-1,seq=[t+(sign*4),t+(sign*3),t+(sign*2),t+sign,t,t-(sign*2)];el('arena').innerHTML='<button id="flash" class="flash" style="width:100%;border:0;color:white">GET READY</button>';var b=el('flash'),i=0;setTimeout(function(){if(locked)return;b.textContent=seq[0];i=1;timer=setInterval(function(){b.textContent=seq[i++%seq.length]},520)},750);b.onclick=function(){if(b.textContent!=='GET READY')answer(Number(b.textContent))}}
}
function shuffle(a){for(var i=a.length-1;i>0;i--){var j=Math.floor(rnd()*(i+1)),x=a[i];a[i]=a[j];a[j]=x}}
function answer(v){if(locked)return;locked=true;clearInterval(timer);Array.prototype.forEach.call(document.querySelectorAll('#arena button'),function(b){b.disabled=true});var good=Math.abs(v-current.target)===1;results.push(good);if(good)score++;var f=el('feedback');f.className='feedback '+(good?'good':'bad');f.textContent=good?'✓ PERFECTLY WRONG':(v===current.target?'✕ TOO ACCURATE!':'✕ OFF BY '+Math.abs(v-current.target));var n=el('nextBtn');n.textContent=round===4?'SEE SCORE':'NEXT';n.classList.remove('hidden')}
el('nextBtn').onclick=function(){if(round<4){round++;render()}else finish()};
function finish(){var elapsed=Math.max(1,Math.round((Date.now()-started)/1000));var rec=saveRun(elapsed);var blocks=results.map(function(x){return'<div class="result-box '+(x?'good':'')+'">'+(x?'✓':'×')+'</div>'}).join('');el('game').innerHTML='<div class="eyebrow">RUN COMPLETE</div><div class="score-ring"><b>'+score+'/5</b><span>ONE OFF</span></div><h2>'+(score===5?'PERFECTLY WRONG.':score>=3?'NICE MISS.':'TOO ACCURATE.')+'</h2><p>'+(score===5?'You missed every target by exactly one.':'The target is a trap. Miss better next run.')+'</p><div class="result-grid">'+blocks+'</div><button id="share" class="primary">SHARE RESULT</button><a class="secondary" href="./v2.html?mode=practice&build=20260923-4">PRACTICE AGAIN</a><a class="secondary" href="./">HOME</a>';el('share').onclick=share}
function saveRun(elapsed){try{var s=JSON.parse(localStorage.getItem(KEY)||'{"runs":0,"best":0,"streak":0,"lastDaily":"","dailyScores":{}}');s.runs=(s.runs||0)+1;s.best=Math.max(s.best||0,score);var old=s.bestPerfectTime||0;s.lastTime=elapsed;if(score===5)s.bestPerfectTime=old?Math.min(old,elapsed):elapsed;if(daily){var today=new Date().toLocaleDateString('en-CA');s.dailyScores=s.dailyScores||{};s.dailyScores[today]=score;if(s.lastDaily!==today){var y=new Date();y.setDate(y.getDate()-1);var yd=y.toLocaleDateString('en-CA');s.streak=s.lastDaily===yd?(s.streak||0)+1:1;s.lastDaily=today}}localStorage.setItem(KEY,JSON.stringify(s));return{newBest:score===5&&(!old||elapsed<old),bestPerfectTime:s.bestPerfectTime||0}}catch(e){return null}}
function share(){var secs=Math.max(1,Math.round((Date.now()-started)/1000));var text='ONE OFF '+(daily?'Daily':'Practice')+' '+score+'/5 • '+secs+'s\n'+results.map(function(x){return x?'🟩':'🟥'}).join('')+'\n🎯 Miss perfectly.';if(navigator.share){navigator.share({title:'ONE OFF',text:text}).catch(function(){})}else if(navigator.clipboard){navigator.clipboard.writeText(text)}}
render();
})();